import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';
import styles from '../../styles/Home.module.css';
import { client } from 'libs/client';

const Home: NextPage = (props: Props) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>{props.data?.title}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>ブログ一覧ページ</main>

			<footer className={styles.footer}>&copy;2022 Kanaru</footer>
		</div>
	);
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
	const data = await client.get({
		endpoint: process.env.NEXT_PUBLIC_MICROCMS_ENDPOINT_CUSTOM,
	});

	return {
		props: {
			data,
		},
	};
};

type Props = {
	data?: {
		createdAt: string;
		updatedAt: string;
		publishedAt: string;
		title: string;
		catch_copy: string;
		header_img: {
			url: string;
			width: number;
			height: number;
		};
	};
};
