import type { NextPage, GetStaticProps } from 'next';
import Head from 'next/head';

import Footer from 'components/organisms/Footer';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Kanaru Official</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<header></header>

			<main>
				<h1>top page</h1>
				<div>コピー</div>
			</main>

			<Footer />
		</div>
	);
};

export default Home;

// export const getStaticProps: GetStaticProps = async () => {
// 	const data = await client.get({
// 		endpoint: process.env.NEXT_PUBLIC_MICROCMS_ENDPOINT_CUSTOM,
// 	});

// 	return {
// 		props: {
// 			data,
// 		},
// 	};
// };

// type Props = {
// 	data?: {
// 		createdAt: string;
// 		updatedAt: string;
// 		publishedAt: string;
// 		title: string;
// 		catch_copy: string;
// 		header_img: {
// 			url: string;
// 			width: number;
// 			height: number;
// 		};
// 	};
// };
